### ISSUE TITLE
Is it possible to add a filter to strip out style/script attributes and empty html tags?

### ISSUE THREAD

**Issue by damianof** [TimeIncUK/flipboard-rss-feed#2]
Is it possible to add a filter to strip out style/script attributes and empty html tags?
Here is some sample content that is currently emitted (notice it includes DIV elements without content that have a style attribute. Probably this come from themes, not sure):

<content:encoded>
<![CDATA[
<div id="upinpost-header" style="clear:both"></div><p>Original painting title &#8220;Ocean Around Midnight&#8221;<br /> Oil on Canvas Panel<br /> 4 x 6 inches<br /> Completed October 2014<br /> Not varnished<br /> Signed  (DF)</p> <p>Tried to capture the different light on the clouds and ocean at night. The inspiration is the beach of Sarasota, Florida. The painting is small and overall pretty dark but with an intense blue overall. It can easily find its place in a smaller room or restroom.</p> <p>Listed on <a title="Ocean Around Midnight - Oil on Canvas Panel - 4 x 6 inches" href="https://www.etsy.com/listing/209702723/ocean-around-midnight-oil-on-canvas" target="_blank">Etsy.com</a></p> <div id="upinpost-footer" style="clear:both"></div>
]]>
</content:encoded>

**Comment by spacedmonkey** [comment]
Fixed in version 1.0.7. Thanks for the feedback!

**Comment by damianof** [comment]
Thank you!
