### ISSUE TITLE
rror on line 1375 at column 112: xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by dgajjar** [TimeIncUK/flipboard-rss-feed#3]
This page contains the following errors:  error on line 1375 at column 112: xmlParseEntityRef: no name Below is a rendering of the page up to the first error.

![screen shot 2015-01-11 at 17 30 12](https://cloud.githubusercontent.com/assets/870322/5696077/a3a29510-99b7-11e4-8da7-4911c7d5599c.png)

**Comment by spacedmonkey** [comment]
Fixed in version 1.0.7. Thanks for the feedback!

**Comment by dgajjar** [comment]
Thank you and you're most welcome !!
